parserOptions:
  sourceType: module
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true

env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

plugins: [ 'react' ]

settings:
  react:
    version: '16'

extends: [ 'plugin:react/recommended' ]
